#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 file"
    exit 1
fi

if [[ -f "$1" ]]; then
    case $1 in
        *.tar.xz)   tar -xvf "$1"                         ;;
        *.tar.bz2)  tar -jxvf "$1"                        ;;
        *.tar.gz)   tar -zxvf "$1"                        ;;
        *.tar)      tar -xvf "$1"                         ;;
        *.tbz2)     tar -jxvf "$1"                        ;;
        *.tgz)      tar -zxvf "$1"                        ;;
        *)          echo "$1 is not a 'tar' file" ;;
    esac
else
    echo "$1 is not a valid file"
fi
